services:
  api:
    container_name: quizzo_test_api
    environment: 
      - PGUSER=quizzo
      - PGHOST=db
      - PGPASSWORD=quizpass
      - PGDATABASE=quizzo_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: quizzo_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=quizzo_test
      - POSTGRES_PASSWORD=quizpass
volumes:
  test_db:
networks: 
  default:
    name: quizzo_test
